### ISSUE TITLE
The issue of underwater datasets

### ISSUE THREAD

**Issue by HanyangZhong** [LaboratoireCosmerTOULON/MAM3SLAM#1]
Hi, after reading your paper and trying out your MAM3SLAM code, I feel that your work is very impressive. 
May I ask if it is possible to access the three underwater datasets mentioned in your paper? 
Currently, I have only tested them on the MH dataset. I just want to use the underwater dataset for some academic research.

**Comment by JulietteDrupt** [comment]
Hi, thank you! The underwater datasets are available here: https://www.seanoe.org/data/00884/99618/ (rosbag + reference trajectories)

**Comment by HanyangZhong** [comment]
Thank you for your link.
But I tried to download it and the dataset shows an unexpected end of archive.
Does the dataset work well in your archive?

**Comment by JulietteDrupt** [comment]
I just checked, and there seems to be an issue with the file download. Thank you for pointing out this issue, I am sorry for the inconvenience. I am contacting the host platform to fix that. I will let you know when it is fixed.

**Comment by JulietteDrupt** [comment]
Hi, sorry for the delay. The data issue should be fixed, if you are still interested. Please let me know if any new issue arises.
